# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cif_channel_core.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cif_channel_core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63if_channel_core.proto\x12\x0f\x63if.channelcore\"\xa6\x01\n\x07\x43hannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\tdirection\x18\x02 \x01(\x0e\x32\x1a.cif.channelcore.Direction\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x15\n\rcustom_config\x18\x04 \x01(\x0c\x12\x11\n\tconnected\x18\x05 \x01(\x08\x12\x16\n\x0e\x63onnected_name\x18\x06 \x01(\t\x12\x0e\n\x06\x66orced\x18\x07 \x01(\x08\"6\n\x08\x43hannels\x12*\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x18.cif.channelcore.Channel\"\\\n\x11\x43onnectSubscriber\x12\x17\n\x0fsubscriber_name\x18\x01 \x01(\t\x12\x16\n\x0epublisher_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63ustom_connect\x18\x03 \x01(\x0c\"G\n\x0c\x46orceChannel\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\x12\x12\n\nforce_data\x18\x03 \x01(\x0c\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty**\n\tDirection\x12\r\n\tPUBLISHER\x10\x00\x12\x0e\n\nSUBSCRIBER\x10\x01\x32\xe7\x01\n\x0b\x43hannelCore\x12\x42\n\x0bGetChannels\x12\x16.cif.channelcore.Empty\x1a\x19.cif.channelcore.Channels\"\x00\x12N\n\rSetConnection\x12\".cif.channelcore.ConnectSubscriber\x1a\x17.cif.channelcore.Status\"\x00\x12\x44\n\x08SetForce\x12\x1d.cif.channelcore.ForceChannel\x1a\x17.cif.channelcore.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cif_channel_core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIRECTION']._serialized_start=485
  _globals['_DIRECTION']._serialized_end=527
  _globals['_CHANNEL']._serialized_start=44
  _globals['_CHANNEL']._serialized_end=210
  _globals['_CHANNELS']._serialized_start=212
  _globals['_CHANNELS']._serialized_end=266
  _globals['_CONNECTSUBSCRIBER']._serialized_start=268
  _globals['_CONNECTSUBSCRIBER']._serialized_end=360
  _globals['_FORCECHANNEL']._serialized_start=362
  _globals['_FORCECHANNEL']._serialized_end=433
  _globals['_STATUS']._serialized_start=435
  _globals['_STATUS']._serialized_end=474
  _globals['_EMPTY']._serialized_start=476
  _globals['_EMPTY']._serialized_end=483
  _globals['_CHANNELCORE']._serialized_start=530
  _globals['_CHANNELCORE']._serialized_end=761
# @@protoc_insertion_point(module_scope)
