# syslog-ng config file for ADAS Replay HIL

options {
    keep-hostname(no);
    owner("lvuser");
    group("ni");
    perm(0644);
};

template t_adas {
    template("$MONTH/$DAY/$YEAR $HOUR:$MIN:$SEC.$MSEC [$LEVEL] $MSGONLY\n");
    template_escape(no);
};

filter f_adas {
    facility(local3);
    level(info..emerg);
    match("adas" value("MSGHDR"));
};

destination adas_replay_hil {
    file("/var/local/natinst/log/adas_replay_hil.log"
         template(t_adas)
    );
};

log {
    source(src);
    filter(f_adas);
    destination(adas_replay_hil);
};
